name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22.0.2'

    - name: Build with Maven
      run: mvn -B package -f IndividualProject/pom.xml

    - name: Run Tests
      run: mvn clean test -f IndividualProject/pom.xml
